name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        directory: ['mern/server', 'mern/client']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ${{ matrix.directory }}/node_modules
        key: ${{ runner.OS }}-build-${{ matrix.directory }}-${{ matrix.node-version }}-${{ hashFiles('${{ matrix.directory }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ matrix.directory }}-${{ matrix.node-version }}-
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.directory }}
        npm ci
