name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install server dependencies
      run: cd mern/server && npm ci
    - name: Install client dependencies
      run: cd mern/client && npm ci
    - name: Start server
      run: cd mern/server && node server.mjs &
    - name: Start client
      run: cd mern/client && npm start &
